package gui;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;

/**
 * Compiles a Diagram into the .dot dialect the engine parser accepts:
 * one node definition or edge per line, mandatory semicolons, no chained
 * edges, int values bare, string values quoted.
 */
public class DotWriter {

	/**
	 * Everything the GUI can cheaply check before handing the file to the
	 * engine, collected so one dialog shows all problems. Sample-rate
	 * consistency, reachability, and scheduling stay in the engine and are
	 * surfaced through its own exception messages.
	 */
	public static List<String> validate(Diagram d) {
		List<String> problems = new ArrayList<>();
		if (d.blocks.isEmpty()) {
			problems.add("the diagram is empty");
			return problems;
		}
		if (d.blocks.stream().noneMatch(b -> b.type.isSource()))
			problems.add("no source block (constant, impulse, sine, or datain)");
		for (Block b : d.blocks) {
			if (d.macros.containsKey(b.name))
				problems.add(b.name + " has the same name as a macro");
			for (BlockType.Param p : b.type.params) {
				String v = b.params.getOrDefault(p.key(), "").trim();
				if (v.isEmpty()) {
					if (p.required())
						problems.add(b.name + " needs a " + p.key());
				} else if (p.isInt() && !d.macros.containsKey(v)) {
					try {
						Integer.parseInt(v);
					} catch (NumberFormatException e) {
						problems.add(b.name + ": " + p.key() + " must be an integer, was \"" + v + "\"");
					}
				}
			}
			int in = d.wiresInto(b).size();
			int out = d.wiresOutOf(b).size();
			switch (b.type.inArity) {
				case NONE -> {}
				case ONE -> { if (in < 1) problems.add(b.name + " has no input"); }
				case TWO -> { if (in != 2) problems.add(b.name + " needs exactly 2 inputs, has " + in); }
				case MANY -> { if (in < 2) problems.add(b.name + " needs at least 2 inputs, has " + in); }
			}
			if (in + out == 0)
				problems.add(b.name + " is not connected to anything");
		}
		return problems;
	}

	public static String toDot(Diagram d) {
		StringBuilder sb = new StringBuilder();
		for (Map.Entry<String, String> e : d.macros.entrySet())
			sb.append("#define ").append(e.getKey()).append(' ')
					.append(macroLiteral(e.getValue())).append('\n');
		sb.append("// generated by dspsim gui\n");
		sb.append("digraph {\n");
		for (Block b : d.blocks) {
			sb.append('\t').append(nodeName(b));
			sb.append(" [type=\"").append(b.type.dotType).append('"');
			for (BlockType.Param p : b.type.params) {
				if (!p.engine())
					continue; // GUI-only setting, meaningless to the engine
				String v = b.params.getOrDefault(p.key(), "").trim();
				if (v.isEmpty())
					continue; // engine applies its own default
				sb.append(", ").append(p.key()).append('=');
				if (p.isInt() || d.macros.containsKey(v))
					sb.append(v); // macro reference: bare identifier, expanded by the preprocessor
				else
					sb.append('"').append(v.replace("\"", "")).append('"');
			}
			sb.append("];\n");
		}
		List<Wire> sorted = new ArrayList<>(d.wires);
		sorted.sort(Comparator.comparing((Wire w) -> w.src.name).thenComparing(w -> w.dst.name));
		for (Wire w : sorted)
			sb.append('\t').append(nodeName(w.src)).append(" -> ").append(nodeName(w.dst)).append(";\n");
		sb.append("}\n");
		return sb.toString();
	}

	public static void write(Diagram d, Path out) throws IOException {
		Files.writeString(out, toDot(d));
	}

	/** #define values are a single NUMBER, STRING, or NAME token; anything
	 *  that doesn't parse as an integer goes out quoted. */
	private static String macroLiteral(String v) {
		try {
			Integer.parseInt(v);
			return v;
		} catch (NumberFormatException e) {
			return '"' + v.replace("\"", "") + '"';
		}
	}

	/** The dialog enforces identifier-safe names; this is the safety net. */
	static String nodeName(Block b) {
		String s = b.name.replaceAll("[^A-Za-z0-9_]", "_");
		if (s.isEmpty() || Character.isDigit(s.charAt(0)))
			s = "_" + s;
		return s;
	}
}
